name: Run MLBB News Bot Every 4 Hours

on:
  schedule:
    - cron: '0 */4 * * *'  # каждые 4 часа
  workflow_dispatch:  # чтобы можно запускать вручную

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python main.py
